local Games = {
  [3623096087] = "", -- Muscle Legends [ LUNARUI V2 ]
  [3623096087] = "", -- Muscle Legends [ FLUENTUI ]
  [3101667897] = "", -- Legends Of Speed
  [126884695634066] = "", -- Grow A Garden
  [2753915549] = "https://github.com/lunarXhvb/Lunar_Hub/raw/refs/heads/main/Games/Blox%20Fruits", -- Blox Fruits [ LunarUI v1 ]
  [4442272183] = "https://github.com/lunarXhvb/Lunar_Hub/raw/refs/heads/main/Games/Blox%20Fruits", -- Blox Fruits [ LunarUI v1 ]
  [7449423635] = "https://github.com/lunarXhvb/Lunar_Hub/raw/refs/heads/main/Games/Blox%20Fruits", -- Blox Fruits [ LunarUI v1 ]
  [2753915549] = "https://github.com/lunarXhvb/Lunar_Hub/raw/refs/heads/main/Games/Blox%20Fruits", -- Blox Fruits [ LunarUI v2 ]
  [4442272183] = "https://github.com/lunarXhvb/Lunar_Hub/raw/refs/heads/main/Games/Blox%20Fruits", -- Blox Fruits [ LunarUI v2 ]
  [7449423635] = "https://github.com/lunarXhvb/Lunar_Hub/raw/refs/heads/main/Games/Blox%20Fruits", -- Blox Fruits [ LunarUI v2 ]
  [537413528] = "", -- Build a Boat For Treasure
  [3956818381] = "", -- Ninja Legends 1
  [5977280685] = "", -- Ninja Legends 2
}
return Games
